<a href="https://colab.research.google.com/github/Tejasri-Pendota/Projects/blob/main/Olympic_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
#from google.colab import drive
#drive.mount('/content/drive')

In [4]:
df = pd.read_csv('/content/drive/MyDrive/athlete_events.csv.zip')
region_df = pd.read_csv('/content/drive/MyDrive/noc_regions.csv')

In [5]:
df.tail()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [6]:
df.shape

(271116, 15)

In [7]:
df = df[df['Season'] == 'Summer']

In [8]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271106,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [9]:
region_df.tail()

     NOC    region        notes
225  YEM     Yemen          NaN
226  YMD     Yemen  South Yemen
227  YUG    Serbia   Yugoslavia
228  ZAM    Zambia          NaN
229  ZIM  Zimbabwe          NaN

In [10]:
df = df.merge(region_df, on='NOC', how='left')
##on='NOC': This specifies the column key (or keys) on which the merge should be performed.
# Both df and region_df should have a column named NOC that will be used to align the data between them.

##how='left': This argument specifies the type of merge to perform. A 'left' join means
#that all rows from the left DataFrame (df) will be retained, and matched rows from the right DataFrame (region_df) will be added.
# If there is no match, the result will contain NaN for columns from region_df

In [11]:
df.tail(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
222547,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN,Argentina,NaN
222548,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN,USA,NaN
222549,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222550,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,Belarus,NaN

In [12]:
df['region'].unique()

array(['China', 'Denmark', 'Netherlands', 'Finland', 'Norway', 'Romania',
       'Estonia', 'France', 'Morocco', 'Spain', 'Egypt', 'Iran',
       'Bulgaria', 'Italy', 'Chad', 'Azerbaijan', 'Sudan', 'Russia',
       'Argentina', 'Cuba', 'Belarus', 'Greece', 'Cameroon', 'Turkey',
       'Chile', 'Mexico', 'USA', 'Nicaragua', 'Hungary', 'Nigeria',
       'Algeria', 'Kuwait', 'Bahrain', 'Pakistan', 'Iraq', 'Syria',
       'Lebanon', 'Qatar', 'Malaysia', 'Germany', 'Canada', 'Ireland',
       'Australia', 'South Africa', 'Eritrea', 'Tanzania', 'Jordan',
       'Tunisia', 'Libya', 'Belgium', 'Djibouti', 'Palestine', 'Comoros',
       'Kazakhstan', 'Brunei', 'India', 'Saudi Arabia', 'Maldives',
       'Ethiopia', 'United Arab Emirates', 'Yemen', 'Indonesia',
       'Philippines', nan, 'Uzbekistan', 'Kyrgyzstan', 'Tajikistan',
       'Japan', 'Republic of Congo', 'Switzerland', 'Brazil', 'Monaco',
       'Israel', 'Uruguay', 'Sweden', 'Sri Lanka', 'Armenia',
       'Ivory Coast', 'Kenya', 'Benin', 'UK', 'Ghana', 'Somalia', 'Niger',
       'Mali', 'Afghanistan', 'Poland', 'Costa Rica', 'Panama', 'Georgia',
       'Slovenia', 'Guyana', 'New Zealand', 'Portugal', 'Paraguay',
       'Angola', 'Venezuela', 'Colombia', 'Bangladesh', 'Peru',
       'El Salvador', 'Puerto Rico', 'Uganda', 'Honduras', 'Ecuador',
       'Turkmenistan', 'Mauritius', 'Seychelles', 'Czech Republic',
       'Luxembourg', 'Mauritania', 'Saint Kitts', 'Trinidad',
       'Dominican Republic', 'Saint Vincent', 'Jamaica', 'Liberia',
       'Suriname', 'Nepal', 'Mongolia', 'Austria', 'Palau', 'Lithuania',
       'Togo', 'Namibia', 'Curacao', 'Ukraine', 'Iceland',
       'American Samoa', 'Samoa', 'Rwanda', 'Croatia', 'Dominica',
       'Haiti', 'Malta', 'Cyprus', 'Guinea', 'Belize', 'Thailand',
       'Bermuda', 'Serbia', 'Sierra Leone', 'Papua New Guinea',
       'Individual Olympic Athletes', 'Oman', 'Fiji', 'Vanuatu',
       'Moldova', 'Bahamas', 'Guatemala', 'Latvia',
       'Virgin Islands, British', 'Mozambique', 'Virgin Islands, US',
       'Central African Republic', 'Madagascar', 'Bosnia and Herzegovina',
       'Guam', 'Cayman Islands', 'Slovakia', 'Barbados', 'Guinea-Bissau',
       'Timor-Leste', 'Democratic Republic of the Congo', 'Gabon',
       'San Marino', 'Laos', 'Botswana', 'South Korea', 'Cambodia',
       'North Korea', 'Solomon Islands', 'Senegal', 'Cape Verde',
       'Equatorial Guinea', 'Boliva', 'Antigua', 'Andorra', 'Zimbabwe',
       'Grenada', 'Saint Lucia', 'Micronesia', 'Myanmar', 'Malawi',
       'Zambia', 'Taiwan', 'Sao Tome and Principe', 'Macedonia',
       'Liechtenstein', 'Montenegro', 'Gambia', 'Cook Islands', 'Albania',
       'Swaziland', 'Burkina Faso', 'Burundi', 'Aruba', 'Nauru',
       'Vietnam', 'Bhutan', 'Marshall Islands', 'Kiribati', 'Tonga',
       'Kosovo', 'South Sudan', 'Lesotho'], dtype=object)

In [13]:
df['region'].unique().shape

(206,)

In [14]:
#check duplicates and null values

df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9189
Height     51857
Weight     53854
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188464
region       370
notes     218151
dtype: int64

In [15]:
df.duplicated().sum()

1385

In [16]:
df.drop_duplicates(inplace =True)
#means that the df DataFrame is modified directly without creating a copy.
#If you want to keep the original DataFrame and create a new one with duplicates dropped,
#use inplace=False

In [17]:
df.duplicated().sum()

0

In [18]:
df['Medal'].value_counts()

Medal
Gold      11456
Bronze    11409
Silver    11212
Name: count, dtype: int64

In [19]:
#df = df.merge(region_df, on='NOC', how='left')

In [20]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN,Argentina,NaN
222548,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN,USA,NaN
222549,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222550,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,Belarus,NaN

In [21]:
df.shape

(221167, 17)

In [22]:
# Remove duplicate columns by selecting only unique columns
df = df.loc[:, ~df.columns.duplicated()]

print("DataFrame shape after removing duplicates:", df.shape)

DataFrame shape after removing duplicates: (221167, 17)

In [23]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN,Argentina,NaN
222548,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN,USA,NaN
222549,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222550,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,Belarus,NaN

In [24]:
# List of specific columns to drop
#columns_to_drop = ['Bronze', 'Gold', 'Silver']

# Drop the specific columns
#df = df.drop(columns=columns_to_drop)

#print("DataFrame shape after dropping specific columns:", df.shape)

In [25]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222547,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN,Argentina,NaN
222548,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN,USA,NaN
222549,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222550,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN
222551,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,Belarus,NaN

In [26]:
B_G_S = pd.get_dummies(df['Medal']) #One Hot encoding

In [27]:
B_G_S = B_G_S.astype('int')
B_G_S

        Bronze  Gold  Silver
0            0     0       0
1            0     0       0
2            0     0       0
3            0     1       0
4            0     0       0
...        ...   ...     ...
222547       0     0       0
222548       0     0       0
222549       0     0       0
222550       0     0       0
222551       0     0       0

[221167 rows x 3 columns]

In [28]:

# Reset the index of both DataFrames to ensure unique and default integer indices
df = df.reset_index(drop=True)
B_G_S = B_G_S.reset_index(drop=True)

In [29]:
df = pd.concat([df ,B_G_S], axis=1)
df.head(5)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0

In [30]:
df.groupby('NOC').sum()[['Gold','Silver','Bronze']].sort_values('Gold' , ascending = False ).reset_index()

     NOC  Gold  Silver  Bronze
0    USA  2472    1333    1197
1    URS   832     635     596
2    GBR   635     729     620
3    GER   592     538     649
4    ITA   518     474     454
..   ...   ...     ...     ...
225  MLT     0       0       0
226  MLI     0       0       0
227  MKD     0       0       1
228  MHL     0       0       0
229  NFL     0       0       0

[230 rows x 4 columns]

here the data has the wrong no. of count of medals , its bcz if a team of 5 had won a medal then its considering it as winning 5 medal

In [31]:
df[(df['NOC'] == 'IND') & (df['Medal'] == 'Gold')]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4183,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4187,2703,Syed Mushtaq Ali,M,22.0,165.0,61.0,India,IND,1964 Summer,1964,Summer,Tokyo,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4454,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4455,2864,Richard James Allen,M,30.0,172.0,NaN,India,IND,1932 Summer,1932,Summer,Los Angeles,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
4456,2864,Richard James Allen,M,34.0,172.0,NaN,India,IND,1936 Summer,1936,Summer,Berlin,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190547,117232,Dung Dung Sylvanus,M,31.0,160.0,62.0,India,IND,1980 Summer,1980,Summer,Moskva,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
192751,118553,Carlyle Carrol Tapsell,M,23.0,182.0,NaN,India,IND,1932 Summer,1932,Summer,Los Angeles,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
192752,118553,Carlyle Carrol Tapsell,M,27.0,182.0,NaN,India,IND,1936 Summer,1936,Summer,Berlin,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
204699,125560,"Max ""Maxie"" Vaz",M,NaN,NaN,NaN,India,IND,1948 Summer,1948,Summer,London,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0
217974,133554,Sayed Muhammad Yusuf,M,NaN,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,0,1,0

In [32]:
medal_tally = df.drop_duplicates(subset = ['Team', 'NOC', 'Games', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'])

In [33]:
medal_tally.shape

(105636, 20)

In [34]:
df.shape

(221167, 20)

In [35]:
medal_tally = medal_tally.groupby('region').sum()[['Gold','Silver','Bronze']].sort_values('Gold' , ascending = False ).reset_index()

In [36]:
medal_tally

         region  Gold  Silver  Bronze
0           USA  1035     802     708
1        Russia   592     498     487
2       Germany   444     457     491
3            UK   278     317     300
4        France   234     256     287
..          ...   ...     ...     ...
200     Albania     0       0       0
201    Kiribati     0       0       0
202      Kuwait     0       0       2
203  Kyrgyzstan     0       1       2
204        Laos     0       0       0

[205 rows x 4 columns]

In [37]:
years = df['Year'].unique().tolist()
years.sort() # Sort the list in place
years.insert(0, 'Overall')

In [38]:
years

['Overall',
 1896,
 1900,
 1904,
 1906,
 1908,
 1912,
 1920,
 1924,
 1928,
 1932,
 1936,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016]

In [39]:
#country = df['region'].dropna().unique()
#country.sort() # Sort the list in place
#country.insert(0, 'Overall')

In [40]:
#country

In [41]:
def fetch_medal_tally(df, year, country):
    medal_df = df.drop_duplicates(subset=['Team', 'NOC', 'Games', 'Year', 'City', 'Sport', 'Event', 'Medal'])
    flag = 0
    if year == 'Overall' and country == 'Overall':
        temp_df = medal_df
    if year == 'Overall' and country != 'Overall':
        flag = 1
        temp_df = medal_df[medal_df['region'] == country]
    if year != 'Overall' and country == 'Overall':
        temp_df = medal_df[medal_df['Year'] == int(year)]
    if year != 'Overall' and country != 'Overall':
        temp_df = medal_df[(medal_df['Year'] == year) & (medal_df['region'] == country)]

    if flag == 1:
        x = temp_df.groupby('Year').sum()[['Gold', 'Silver', 'Bronze']].sort_values('Year').reset_index()
    else:
        x = temp_df.groupby('region').sum()[['Gold', 'Silver', 'Bronze']].sort_values('Gold',ascending=False).reset_index()

        return x

In [42]:
result = fetch_medal_tally( df, year = 2016 , country = 'UK')

In [43]:
print(result)

  region  Gold  Silver  Bronze
0     UK    27      23      17

In [44]:
df['Sport'].unique()

array(['Basketball', 'Judo', 'Football', 'Tug-Of-War', 'Athletics',
       'Swimming', 'Badminton', 'Sailing', 'Gymnastics',
       'Art Competitions', 'Handball', 'Weightlifting', 'Wrestling',
       'Water Polo', 'Hockey', 'Rowing', 'Fencing', 'Equestrianism',
       'Shooting', 'Boxing', 'Taekwondo', 'Cycling', 'Diving', 'Canoeing',
       'Tennis', 'Modern Pentathlon', 'Golf', 'Softball', 'Archery',
       'Volleyball', 'Synchronized Swimming', 'Table Tennis', 'Baseball',
       'Rhythmic Gymnastics', 'Rugby Sevens', 'Trampolining',
       'Beach Volleyball', 'Triathlon', 'Rugby', 'Lacrosse', 'Polo',
       'Cricket', 'Ice Hockey', 'Racquets', 'Motorboating', 'Croquet',
       'Figure Skating', 'Jeu De Paume', 'Roque', 'Basque Pelota',
       'Alpinism', 'Aeronautics'], dtype=object)

In [45]:
df['Year'].unique()

array([1992, 2012, 1920, 1900, 1932, 1952, 2000, 1996, 1912, 1924, 1948,
       2008, 2016, 2004, 1984, 1968, 1972, 1988, 1936, 1956, 1960, 1928,
       1976, 1980, 1964, 1906, 1904, 1908, 1896])

In [46]:
df['Name'].unique().shape

(116122,)

In [47]:
df['region'].unique().shape

(206,)

In [48]:
df['Event'].unique()

array(["Basketball Men's Basketball", "Judo Men's Extra-Lightweight",
       "Football Men's Football", "Tug-Of-War Men's Tug-Of-War",
       "Athletics Women's 100 metres",
       "Athletics Women's 4 x 100 metres Relay",
       "Swimming Men's 400 metres Freestyle", "Badminton Men's Singles",
       "Sailing Women's Windsurfer",
       "Swimming Men's 200 metres Breaststroke",
       "Swimming Men's 400 metres Breaststroke",
       "Gymnastics Men's Individual All-Around",
       "Gymnastics Men's Team All-Around",
       "Gymnastics Men's Floor Exercise", "Gymnastics Men's Horse Vault",
       "Gymnastics Men's Parallel Bars",
       "Gymnastics Men's Horizontal Bar", "Gymnastics Men's Rings",
       "Gymnastics Men's Pommelled Horse", "Athletics Men's Shot Put",
       'Art Competitions Mixed Sculpturing, Unknown Event',
       "Handball Women's Handball",
       "Weightlifting Women's Super-Heavyweight",
       "Wrestling Men's Light-Heavyweight, Greco-Roman",
       "Gymnastics Men's Team All-Around, Free System",
       "Water Polo Men's Water Polo",
       'Sailing Mixed Three Person Keelboat', "Hockey Women's Hockey",
       "Rowing Men's Lightweight Double Sculls",
       "Athletics Men's Pole Vault", "Athletics Men's High Jump",
       "Sailing Men's Two Person Dinghy", "Athletics Men's 1,500 metres",
       "Swimming Men's 100 metres Butterfly",
       "Swimming Men's 200 metres Butterfly",
       "Swimming Men's 4 x 100 metres Medley Relay",
       "Football Women's Football", "Fencing Men's Foil, Individual",
       "Fencing Men's epee, Individual", "Fencing Men's epee, Team",
       'Sailing Mixed 8 metres',
       'Equestrianism Mixed Jumping, Individual',
       "Shooting Men's Small-Bore Rifle, Prone, 50 metres",
       "Shooting Men's Rapid-Fire Pistol, 25 metres",
       "Shooting Men's Trap", "Athletics Men's 4 x 100 metres Relay",
       "Athletics Men's Long Jump", "Boxing Men's Light-Welterweight",
       "Athletics Women's Javelin Throw",
       "Wrestling Men's Heavyweight, Freestyle",
       "Taekwondo Men's Flyweight", "Boxing Men's Heavyweight",
       "Athletics Men's 5,000 metres",
       "Cycling Men's Road Race, Individual",
       "Cycling Men's Road Race, Team", "Weightlifting Men's Lightweight",
       "Weightlifting Men's Middleweight", "Rowing Men's Coxless Pairs",
       "Judo Men's Half-Middleweight", "Taekwondo Women's Flyweight",
       "Boxing Men's Flyweight", "Basketball Women's Basketball",
       "Diving Men's Platform",
       "Canoeing Men's Canadian Doubles, 500 metres",
       "Canoeing Men's Canadian Doubles, 1,000 metres",
       "Canoeing Men's Kayak Fours, 1,000 metres",
       "Handball Men's Handball", "Rowing Women's Coxless Pairs",
       "Boxing Men's Middleweight", "Judo Men's Lightweight",
       "Boxing Men's Featherweight", "Tennis Men's Doubles",
       'Shooting Mixed Skeet', "Wrestling Men's Featherweight, Freestyle",
       'Sailing Mixed Two Person Heavyweight Dinghy',
       "Athletics Women's Shot Put", "Rowing Men's Coxed Eights",
       "Cycling Women's Sprint", "Cycling Women's 500 metres Time Trial",
       "Athletics Men's 110 metres Hurdles", 'Shooting Mixed Trap',
       "Athletics Women's Marathon", "Athletics Men's 100 metres",
       "Fencing Men's Foil, Team", "Fencing Men's Sabre, Team",
       "Swimming Men's 100 metres Freestyle",
       "Swimming Men's 4 x 200 metres Freestyle Relay",
       "Boxing Men's Lightweight", "Modern Pentathlon Men's Individual",
       "Boxing Men's Welterweight", "Rowing Men's Quadruple Sculls",
       "Rowing Men's Double Sculls", "Rowing Men's Coxed Pairs",
       "Athletics Men's 400 metres Hurdles", "Athletics Men's 400 metres",
       "Athletics Men's Hammer Throw",
       "Weightlifting Men's Featherweight", "Athletics Men's 800 metres",
       "Hockey Men's Hockey", "Rowing Women's Single Sculls",
       "Swimming Men's 50 metres Freestyle",
       "Weightlifting Women's Featherweight",
       "Water Polo Women's Water Polo", "Weightlifting Men's Heavyweight",
       'Equestrianism Mixed Three-Day Event, Individual',
       'Equestrianism Mixed Three-Day Event, Team',
       "Sailing Women's Three Person Keelboat",
       "Cycling Women's Road Race, Individual", "Golf Women's Individual",
       "Softball Women's Softball", "Archery Women's Individual",
       "Wrestling Men's Heavyweight, Greco-Roman",
       "Volleyball Men's Volleyball", "Taekwondo Women's Heavyweight",
       "Synchronized Swimming Women's Duet",
       "Synchronized Swimming Women's Team",
       "Taekwondo Women's Featherweight", "Athletics Men's Marathon",
       "Athletics Men's 4 x 400 metres Relay",
       "Athletics Men's 10,000 metres", "Athletics Women's 3,000 metres",
       "Diving Women's Platform", "Shooting Men's Air Rifle, 10 metres",
       "Athletics Men's 200 metres", "Weightlifting Men's Flyweight",
       "Swimming Men's 100 metres Backstroke",
       "Weightlifting Men's Light-Heavyweight",
       "Wrestling Men's Lightweight, Greco-Roman",
       "Fencing Men's Sabre, Individual",
       "Wrestling Men's Super-Heavyweight, Greco-Roman",
       "Shooting Men's Free Pistol, 50 metres",
       "Shooting Men's Air Pistol, 10 metres",
       "Rowing Men's Coxless Fours", "Boxing Men's Light-Flyweight",
       "Boxing Men's Super-Heavyweight",
       "Wrestling Men's Flyweight, Greco-Roman",
       "Shooting Women's Air Rifle, 10 metres",
       "Weightlifting Men's Middle-Heavyweight",
       "Athletics Men's Javelin Throw", "Volleyball Women's Volleyball",
       "Wrestling Men's Welterweight, Greco-Roman",
       "Wrestling Men's Middleweight, Greco-Roman",
       "Athletics Men's 3,000 metres Steeplechase",
       "Wrestling Men's Middleweight, Freestyle",
       "Swimming Women's 100 metres Backstroke",
       "Swimming Women's 200 metres Backstroke",
       "Swimming Women's 4 x 100 metres Medley Relay",
       "Wrestling Men's Light-Heavyweight, Freestyle",
       "Modern Pentathlon Men's Team", "Boxing Men's Bantamweight",
       "Athletics Women's 200 metres", "Table Tennis Women's Singles",
       "Table Tennis Women's Doubles", "Shooting Men's Skeet",
       "Swimming Women's 50 metres Freestyle",
       "Shooting Men's Small-Bore Rifle, Three Positions, 50 metres",
       "Athletics Men's Triple Jump", "Weightlifting Women's Lightweight",
       "Athletics Women's Long Jump", "Fencing Women's epee, Individual",
       "Swimming Men's 200 metres Freestyle",
       "Swimming Men's 4 x 100 metres Freestyle Relay",
       "Swimming Men's 200 metres Backstroke",
       "Swimming Men's 200 metres Individual Medley",
       "Swimming Men's 400 metres Individual Medley",
       "Badminton Women's Singles", "Boxing Men's Light-Middleweight",
       "Tennis Men's Singles", "Wrestling Men's Bantamweight, Freestyle",
       "Wrestling Men's Flyweight, Freestyle",
       "Athletics Women's 5,000 metres",
       "Weightlifting Women's Light-Heavyweight",
       "Weightlifting Women's Heavyweight",
       "Athletics Men's Discus Throw", "Taekwondo Men's Featherweight",
       "Taekwondo Men's Welterweight", "Judo Men's Heavyweight",
       "Cycling Men's Sprint", "Wrestling Men's Lightweight, Freestyle",
       "Baseball Men's Baseball", "Rowing Men's Coxed Fours",
       "Cycling Men's 100 kilometres Team Time Trial",
       "Rhythmic Gymnastics Women's Group",
       'Art Competitions Mixed Architecture, Designs For Town Planning',
       'Art Competitions Mixed Architecture, Architectural Designs',
       "Gymnastics Women's Individual All-Around",
       "Gymnastics Women's Team All-Around",
       "Gymnastics Women's Floor Exercise",
       "Gymnastics Women's Horse Vault", "Gymnastics Women's Uneven Bars",
       "Gymnastics Women's Balance Beam", "Diving Women's Springboard",
       "Diving Women's Synchronized Springboard",
       "Athletics Women's 10,000 metres", 'Sailing Mixed 7 metres',
       "Judo Women's Half-Middleweight", "Athletics Men's Decathlon",
       "Wrestling Men's Middleweight A, Greco-Roman",
       "Athletics Women's Discus Throw",
       "Swimming Women's 4 x 100 metres Freestyle Relay",
       "Athletics Women's 1,500 metres",
       "Shooting Women's Air Pistol, 10 metres",
       "Shooting Women's Sporting Pistol, 25 metres",
       "Canoeing Men's Kayak Doubles, 500 metres",
       "Canoeing Men's Kayak Singles, 500 metres",
       "Canoeing Men's Kayak Singles, 1,000 metres",
       "Shooting Men's Running Target, 50 metres",
       "Judo Women's Half-Heavyweight", "Athletics Women's Pole Vault",
       "Rugby Sevens Women's Rugby Sevens", "Table Tennis Men's Team",
       "Rowing Women's Coxed Eights",
       "Athletics Women's 4 x 400 metres Relay",
       "Cycling Men's 1,000 metres Time Trial",
       "Cycling Men's Individual Pursuit, 4,000 metres",
       "Wrestling Men's Welterweight, Freestyle",
       "Wrestling Men's Bantamweight, Greco-Roman",
       "Rowing Women's Lightweight Double Sculls",
       "Athletics Women's 800 metres",
       "Rowing Women's Coxed Quadruple Sculls",
       "Rhythmic Gymnastics Women's Individual",
       "Canoeing Men's Kayak Singles, Slalom", "Archery Men's Individual",
       "Archery Men's Team", "Athletics Women's 400 metres",
       "Trampolining Men's Individual",
       "Beach Volleyball Men's Beach Volleyball",
       "Cycling Women's Mountainbike, Cross-Country",
       "Athletics Men's Javelin Throw, Both Hands",
       "Triathlon Women's Olympic Distance",
       "Gymnastics Women's Team Portable Apparatus",
       "Cycling Men's Mountainbike, Cross-Country",
       "Athletics Women's 400 metres Hurdles", "Diving Men's Springboard",
       "Wrestling Men's Featherweight, Greco-Roman",
       "Table Tennis Men's Singles", 'Art Competitions Mixed Painting',
       "Judo Men's Open Class", "Rowing Women's Quadruple Sculls",
       "Gymnastics Men's Team All-Around, Swedish System",
       "Athletics Women's Pentathlon",
       'Art Competitions Mixed Painting, Unknown Event',
       "Cycling Men's Team Pursuit, 4,000 metres",
       "Weightlifting Women's Middleweight",
       "Swimming Men's 1,500 metres Freestyle",
       "Wrestling Women's Light-Heavyweight, Freestyle",
       "Swimming Women's 100 metres Freestyle",
       "Equestrianism Men's Jumping, Individual",
       "Equestrianism Men's Jumping, Team",
       "Equestrianism Men's Three-Day Event, Individual",
       "Equestrianism Men's Three-Day Event, Team",
       "Athletics Women's High Jump",
       "Canoeing Women's Kayak Fours, 500 metres",
       "Sailing Men's One Person Dinghy",
       "Trampolining Women's Individual",
       'Art Competitions Mixed Literature', "Judo Men's Middleweight",
       "Judo Men's Half-Lightweight", "Fencing Women's Foil, Team",
       "Swimming Women's 200 metres Butterfly",
       "Swimming Women's 400 metres Individual Medley",
       "Golf Men's Individual", "Athletics Men's Standing High Jump",
       "Athletics Men's Standing Long Jump",
       "Athletics Men's 20 kilometres Walk",
       "Swimming Men's 220 yard Freestyle",
       "Swimming Men's 880 yard Freestyle",
       "Swimming Men's One Mile Freestyle",
       "Swimming Men's 4 x 50 Yard Freestyle Relay",
       "Swimming Men's Plunge For Distance",
       "Shooting Men's Free Rifle, Three Positions, 300 metres",
       "Shooting Men's Military Rifle, Three Positions, 300 metres",
       "Shooting Men's Military Rifle, Any Position, 600 metres",
       "Shooting Men's Military Rifle, 200, 400, 500 and 600 metres, Team",
       "Shooting Men's Military Rifle, Prone, 300 metres",
       "Judo Men's Half-Heavyweight", "Archery Women's Team",
       "Athletics Men's 50 kilometres Walk",
       "Rowing Women's Double Sculls", 'Sailing Mixed 6 metres',
       "Boxing Men's Light-Heavyweight", "Boxing Women's Flyweight",
       "Athletics Women's 100 metres Hurdles",
       "Athletics Men's Discus Throw, Greek Style",
       'Sailing Mixed One Person Dinghy',
       "Wrestling Women's Heavyweight, Freestyle",
       'Badminton Mixed Doubles', "Fencing Women's Foil, Individual",
       'Sailing Mixed Two Person Keelboat',
       "Shooting Men's Military Rifle, 300 metres and 600 metres, Prone, Team",
       "Table Tennis Men's Doubles",
       "Wrestling Men's Light-Flyweight, Freestyle",
       "Wrestling Women's Featherweight, Freestyle",
       "Swimming Women's 200 metres Freestyle",
       "Swimming Women's 400 metres Freestyle",
       "Swimming Women's 200 metres Individual Medley",
       "Sailing Men's Windsurfer",
       "Shooting Men's Running Target, Single Shot",
       "Shooting Men's Running Target, Double Shot",
       "Rugby Sevens Men's Rugby Sevens",
       "Wrestling Women's Lightweight, Freestyle",
       "Modern Pentathlon Women's Individual",
       "Canoeing Men's Canadian Doubles, Slalom",
       "Judo Women's Half-Lightweight", "Diving Women's Plain High",
       "Equestrianism Men's Dressage, Individual",
       "Equestrianism Men's Dressage, Team",
       "Tennis Women's Singles, Covered Courts",
       "Diving Men's Plain High",
       'Shooting Mixed Small-Bore Rifle, Three Positions, 50 metres',
       'Shooting Mixed Small-Bore Rifle, Prone, 50 metres',
       "Swimming Women's 800 metres Freestyle",
       "Sailing Women's Two Person Dinghy",
       "Shooting Men's Free Pistol, 50 metres, Team",
       "Shooting Men's Free Rifle, Three Positions, 300 metres, Team",
       "Shooting Men's Military Rifle, Prone, 300 metres, Team",
       "Shooting Men's Military Rifle, Prone, 600 metres, Team",
       "Shooting Men's Military Rifle, Standing, 300 metres, Team",
       "Shooting Men's Free Rifle, Prone, 600 metres",
       "Shooting Men's Free Rifle, 400, 600 and 800 metres, Team",
       "Rowing Men's Single Sculls",
       "Cycling Men's Tandem Sprint, 2,000 metres",
       "Athletics Women's Heptathlon", "Cycling Men's Points Race",
       "Synchronized Swimming Women's Solo",
       'Equestrianism Mixed Dressage, Individual',
       'Equestrianism Mixed Dressage, Team',
       "Swimming Men's 100 metres Breaststroke",
       'Shooting Mixed Free Pistol, 50 metres', "Sailing Women's Skiff",
       "Canoeing Men's Kayak Doubles, 10,000 metres",
       "Triathlon Men's Olympic Distance",
       "Sailing Women's One Person Dinghy",
       "Rowing Men's 17-Man Naval Rowing Boats",
       "Beach Volleyball Women's Beach Volleyball",
       "Weightlifting Men's Super-Heavyweight",
       "Rowing Men's Lightweight Coxless Fours",
       "Wrestling Men's Light-Flyweight, Greco-Roman",
       "Canoeing Men's Canadian Singles, 1,000 metres",
       'Sailing Mixed 5.5 metres', 'Equestrianism Mixed Jumping, Team',
       "Diving Men's Synchronized Platform",
       "Canoeing Women's Kayak Singles, Slalom",
       "Weightlifting Women's Flyweight",
       "Swimming Women's 100 metres Breaststroke",
       "Swimming Women's 200 metres Breaststroke",
       "Wrestling Men's Middleweight B, Greco-Roman",
       "Athletics Men's Stone Throw",
       "Athletics Men's Javelin Throw, Freestyle",
       "Athletics Men's Pentathlon (Ancient)",
       "Shooting Women's Small-Bore Rifle, Three Positions, 50 metres",
       "Swimming Women's 100 metres Butterfly",
       "Weightlifting Men's Heavyweight I",
       "Athletics Women's 3,000 metres Steeplechase",
       "Athletics Men's Shot Put, Both Hands", "Shooting Women's Trap",
       "Badminton Men's Doubles",
       "Swimming Women's 4 x 200 metres Freestyle Relay",
       "Athletics Men's 10 kilometres Walk",
       "Athletics Women's 20 kilometres Walk",
       "Athletics Women's 80 metres Hurdles",
       "Sailing Men's One Person Heavyweight Dinghy",
       'Art Competitions Mixed Painting, Paintings',
       'Tennis Mixed Doubles, Covered Courts', "Cycling Men's Madison",
       'Art Competitions Mixed Sculpturing, Statues', "Rugby Men's Rugby",
       "Weightlifting Men's Heavyweight II",
       "Canoeing Women's Kayak Doubles, 500 metres",
       "Cycling Men's Individual Time Trial", "Judo Women's Heavyweight",
       "Canoeing Men's Kayak Doubles, 1,000 metres",
       "Gymnastics Men's Individual All-Around, 5 Events",
       "Wrestling Men's Super-Heavyweight, Freestyle",
       "Fencing Women's Sabre, Team", "Shooting Men's Double Trap",
       "Weightlifting Men's Bantamweight", "Taekwondo Men's Heavyweight",
       'Sailing Mixed Windsurfer', "Taekwondo Women's Welterweight",
       'Shooting Mixed Free Rifle, Three Positions, 300 metres',
       "Cycling Men's 50 kilometres",
       'Shooting Mixed Rapid-Fire Pistol, 25 metres',
       "Cycling Men's 333 metres Time Trial",
       "Cycling Men's 20 kilometres",
       "Canoeing Men's Kayak Singles, 10,000 metres",
       'Sailing Mixed Open', 'Sailing Mixed 1-2 Ton',
       "Canoeing Men's Canadian Singles, Slalom",
       'Sailing Mixed Multihull', "Badminton Women's Doubles",
       "Diving Women's Synchronized Platform",
       "Athletics Women's Triple Jump",
       'Art Competitions Mixed Painting, Drawings And Water Colors',
       "Shooting Men's Dueling Pistol, 30 metres",
       "Boxing Women's Lightweight", "Cycling Women's BMX",
       "Canoeing Men's Kayak Doubles, 200 metres",
       "Fencing Men's Sabre, Masters, Individual",
       "Lacrosse Men's Lacrosse",
       "Canoeing Women's Kayak Singles, 500 metres",
       "Athletics Women's 10 kilometres Walk", 'Sailing Mixed 12 metres',
       "Judo Women's Extra-Lightweight",
       "Diving Men's Synchronized Springboard",
       "Rowing Men's Coxed Fours, Outriggers",
       "Gymnastics Men's Rope Climbing",
       'Sailing Mixed Two Person Dinghy',
       'Art Competitions Mixed Architecture, Unknown Event',
       "Archery Men's Target Archery, 28 metres, Team",
       "Archery Men's Target Archery, 33 metres, Team",
       "Archery Men's Target Archery, 50 metres, Team",
       "Shooting Men's Running Target, 10 metres", "Polo Men's Polo",
       "Rowing Men's Coxed Fours, Inriggers", "Cycling Men's BMX",
       'Art Competitions Mixed Sculpturing',
       "Athletics Men's Cross-Country, Individual",
       "Athletics Men's Cross-Country, Team", 'Sailing Mixed 40 metres',
       "Gymnastics Men's Club Swinging", "Tennis Women's Singles",
       'Tennis Mixed Doubles', "Tennis Women's Doubles",
       "Judo Women's Middleweight", "Judo Women's Lightweight",
       "Canoeing Women's Kayak Singles, 200 metres",
       "Canoeing Men's Kayak Relay 4 x 500 metres",
       "Athletics Men's 3,000 metres, Team",
       "Shooting Men's Small-Bore Rifle, Prone, 50 and 100 yards",
       "Shooting Men's Small-Bore Rifle, 50 and 100 yards, Team",
       "Shooting Men's Small-Bore Rifle, Disappearing Target, 25 yards",
       "Shooting Men's Small-Bore Rifle, Moving Target, 25 yards",
       "Shooting Men's Military Pistol, Team",
       "Rowing Women's Coxed Fours",
       "Weightlifting Men's Unlimited, One Hand",
       "Canoeing Men's Canadian Singles, 500 metres",
       "Fencing Men's Foil, Masters, Individual",
       "Fencing Men's epee, Masters, Individual",
       "Gymnastics Men's Individual All-Around, Field Sports",
       "Gymnastics Men's Individual All-Around, Apparatus Work",
       'Art Competitions Mixed Music, Compositions For Solo Or Chorus',
       "Fencing Women's epee, Team",
       "Swimming Men's 4,000 metres Freestyle",
       "Swimming Men's Underwater Swimming", 'Sailing Mixed Skiff',
       "Shooting Men's Military Rifle, 200/500/600/800/900/1,000 Yards, Team",
       "Shooting Men's Running Target, Single And Double Shot",
       "Shooting Men's Small-Bore Rifle, Any Position, 50 metres",
       "Shooting Men's Small-Bore Rifle, Disappearing Target, 25 metres",
       "Swimming Women's 10 kilometres Open Water",
       "Cycling Men's Team Pursuit, 1,980 yards",
       "Cycling Men's 5,000 metres", "Cycling Men's 100 kilometres",
       "Cricket Men's Cricket",

In [49]:
nations_over_time = df.drop_duplicates(["Year" ,"region"])['Year'].value_counts().reset_index().sort_values('Year')

In [50]:
nations_over_time = nations_over_time.rename(columns = {'Year' : 'Edition' ,'count' : 'No. of Countries'})

In [51]:
import plotly.express as px

In [52]:
fig = px.line(nations_over_time , x ="Edition" , y = "No. of Countries")
fig.show()

In [53]:
temp_df = df.drop_duplicates(subset = ['Team', 'NOC', 'Games', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'])

In [54]:
new_df = temp_df[temp_df['region'] == 'India']
final_df = new_df.groupby('Year').count()['Medal'].reset_index()

In [55]:
fig = px.line(final_df , x ="Year" , y = "Medal")
fig.show()

In [56]:
print(type(nations_over_time))

<class 'pandas.core.frame.DataFrame'>

In [57]:
events_over_years = df.drop_duplicates(['Year' , 'Event'])['Year'].value_counts().reset_index().sort_values('Year')

In [58]:
fig = px.line(events_over_years , x ="Year" , y="count")
fig.show()

In [70]:
def most_sucessful(df, sport):
    temp_df = df.dropna(subset=['Medal'])

    if sport !='Overall' :
       temp_df = temp_df[temp_df['Sport'] == sport]

    x = temp_df['Name'].value_counts().reset_index().merge(df ,left_on ='ID' , right_on ='Name' , how = 'left' )[['ID' ,'Name', 'Sport' ,'region']].drop_duplicates('ID').sort_values('ID' , ascending = False)
    return x

In [113]:
def most_successful(df, sport):
    temp_df = df.dropna(subset=['Medal'])

    if sport != 'Overall':
        temp_df = temp_df[temp_df['Sport'] == sport]

    x = temp_df['Name'].value_counts().reset_index()
    x = x.head(15).merge(df, left_on='Name', right_on='Name', how='left')[
        ['Name','Medal', 'Sport', 'region']].drop_duplicates('Name')
    return x

In [117]:
def most_successful(df, sport):
    # Drop rows where 'Medal' is NaN
    temp_df = df.dropna(subset=['Medal'])

    # Filter by sport if it's not 'Overall'
    if sport != 'Overall':
        temp_df = temp_df[temp_df['Sport'] == sport]

    # Count the number of medals each athlete has won
    x = temp_df['Name'].value_counts().reset_index()

    print(x)
    x.columns = ['Name', 'Medal_Count']  # Rename columns for clarity

    # Merge to get additional info like 'Sport' and 'region'
    x = x.merge(df[['Name', 'Sport', 'region']], on='Name', how='left').drop_duplicates('Name')

    return x.head(15)  # Return top 15 athletes

# Usage example
most_successful(df, 'Overall')

                                     Name  count
0                 Michael Fred Phelps, II     28
1      Larysa Semenivna Latynina (Diriy-)     18
2            Nikolay Yefimovich Andrianov     15
3                     Edoardo Mangiarotti     13
4             Borys Anfiyanovych Shakhlin     13
...                                   ...    ...
24540                       Iris Zscherpe      1
24541                      Ronald Zoodsma      1
24542                     Khristos Zorbas      1
24543                          Aljoa orga      1
24544                        Milenko Zori      1

[24545 rows x 2 columns]

,Name,Medal_Count,Sport,region
0,"Michael Fred Phelps, II",28,Swimming,USA
30,Larysa Semenivna Latynina (Diriy-),18,Gymnastics,Russia
49,Nikolay Yefimovich Andrianov,15,Gymnastics,Russia
73,Edoardo Mangiarotti,13,Fencing,Italy
87,Borys Anfiyanovych Shakhlin,13,Gymnastics,Russia
111,Takashi Ono,13,Gymnastics,Japan
144,Ryan Steven Lochte,12,Swimming,USA
158,Sawao Kato,12,Gymnastics,Japan
182,"Dara Grace Torres (-Hoffman, -Minas)",12,Swimming,USA
195,Birgit Fischer-Schmidt,12,Canoeing,Germany
208,Natalie Anne Coughlin (-Hall),12,Swimming,USA
220,Aleksey Yuryevich Nemov,12,Gymnastics,Russia
241,Paavo Johannes Nurmi,12,Athletics,Finland
253,"Jennifer Elisabeth ""Jenny"" Thompson (-Cumpelik)",12,Swimming,USA
270,Vra slavsk (-Odloilov),11,Gymnastics,Czech Republic

In [116]:
 most_successful(df, 'Overall')

,Name,Medal_Count,Sport,region
0,"Michael Fred Phelps, II",28,Swimming,USA
30,Larysa Semenivna Latynina (Diriy-),18,Gymnastics,Russia
49,Nikolay Yefimovich Andrianov,15,Gymnastics,Russia
73,Edoardo Mangiarotti,13,Fencing,Italy
87,Borys Anfiyanovych Shakhlin,13,Gymnastics,Russia
111,Takashi Ono,13,Gymnastics,Japan
144,Ryan Steven Lochte,12,Swimming,USA
158,Sawao Kato,12,Gymnastics,Japan
182,"Dara Grace Torres (-Hoffman, -Minas)",12,Swimming,USA
195,Birgit Fischer-Schmidt,12,Canoeing,Germany
208,Natalie Anne Coughlin (-Hall),12,Swimming,USA
220,Aleksey Yuryevich Nemov,12,Gymnastics,Russia
241,Paavo Johannes Nurmi,12,Athletics,Finland
253,"Jennifer Elisabeth ""Jenny"" Thompson (-Cumpelik)",12,Swimming,USA
270,Vra slavsk (-Odloilov),11,Gymnastics,Czech Republic

In [72]:
df

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,0,0,0
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,0,0,0
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,0,0,0
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,0,1,0
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221162,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN,Argentina,NaN,0,0,0
221163,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN,USA,NaN,0,0,0
221164,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN,0,0,0
221165,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN,Russia,NaN,0,0,0
221166,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN,Belarus,NaN,0,0,0